title: Toby Griffin
description: >-
  Tech articles by bygri
baseurl: ""
url: "https://www.tobygriffin.dev"
github_username:  bygri
google_analytics: UA-113082283-1

theme: minima

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap

exclude:
  - rundev.sh
  - Gemfile
  - Gemfile.lock
