title: bygri
description: >-
  Tech by bygri
baseurl: ""
url: "https://bygri.github.io"
github_username:  bygri
google_analytics: UA-113082283-1

markdown: kramdown
theme: minima

exclude:
  - Dockerfile-dev
  - Gemfile
  - Gemfile.lock
